image: Visual Studio 2017

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn dist

deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: 6rqYqTWWocrx45Pb827mB6BJxougvQn/QabUVH2N5e6pyecrRMDKKlfOBJo6BtjS # your encrypted token from GitHub
  artifact: dist\*.exe
  draft: false
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: false

test: off
