image: Visual Studio 2017

environment:
  GH_TOKEN:
    secure: 6rqYqTWWocrx45Pb827mB6BJxougvQn/QabUVH2N5e6pyecrRMDKKlfOBJo6BtjS

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn dist

deploy: off

test: off
